framework:
    cache:
        app: cache.adapter.filesystem

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

when@test:
    cache:
        app: cache.adapter.null