services:
    App\System\Domain\Event\DomainEventStoreRepository:
        alias: App\System\Infrastructure\Domain\Event\DbalDomainEventStoreRepository

    App\Lotr\Domain\Model\Faction\FactionRepository:
        alias: App\Lotr\Infrastructure\Domain\Model\Faction\DbalFactionRepository
