services:
    connection.dbal:
        class: Doctrine\DBAL\Connection
        factory: 'Doctrine\DBAL\DriverManager::getConnection'
        arguments:
            $params:
                driver: 'pdo_pgsql'
                server_version: '15.7'
                charset: UTF8
                default_table_options:
                    charset: UTF8
                url: '%write_db%'
            $config: '@connection.dbal.configuration'

    connection.dbal.configuration:
        class: Doctrine\DBAL\Configuration
