services:
    App\System\Domain\Event\DomainEventStoreRepository:
        alias: App\System\Infrastructure\Domain\Event\DbalDomainEventStoreRepository

    App\Users\Domain\Model\User\UserRepository:
        alias: App\Users\Infrastructure\Domain\Model\User\DbalUserRepository
