system_routes:
    resource: routes/system_routes.yaml

users_routes:
    resource: context/users/users_routes.yaml
    prefix: /users

marketplace_routes:
    resource: context/marketplace/marketplace_routes.yaml
    prefix: /marketplace
