services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Marketplace\Infrastructure\Adapter\RestApi\:
        resource: '../../../src/Marketplace/Infrastructure/Adapter/RestApi/*'
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@messenger_command.bus'
            Symfony\Component\Messenger\MessageBusInterface $queryBus: '@messenger_query.bus'
        tags:
            - { name: controller.service_arguments }

    App\Marketplace\Infrastructure\Adapter\Command\:
        resource: '../../../src/Marketplace/Infrastructure/Adapter/Command/*'
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@messenger_command.bus'

    App\Marketplace\Infrastructure\Adapter\Amqp\:
        resource: '../../../src/Marketplace/Infrastructure/Adapter/Amqp/*'
        autowire: true
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: messenger_event.bus }

    App\Marketplace\Application\Command\:
        autowire: true
        autoconfigure: false
        resource: '../../../src/Marketplace/Application/Command/*/*/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger_command.bus }

    App\Marketplace\Application\Query\:
        autowire: true
        autoconfigure: false
        resource: '../../../src/Marketplace/Application/Query/*/*/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: messenger_query.bus }

    App\Marketplace\Domain\Service\Event\ProviderEventsExtractor\ProviderEventsExtractor:
        class: App\Marketplace\Infrastructure\Domain\Service\Event\HttpProviderEventsExtractor
        arguments:
            $providerClient: '@http.client.provider'

    http.client.provider:
        class: GuzzleHttp\Client
        arguments:
            -   base_uri: '%env(PROVIDER_URI)%'
                headers:
                    user-agent: 'skeleton/marketplace'
