#factions
factions_create:
    path: /v1/factions
    controller: \App\Lotr\Infrastructure\Adapter\RestApi\FactionsController::create
    methods: [POST]

factions_by_id:
    path: /v1/factions/{id}
    controller: \App\Lotr\Infrastructure\Adapter\RestApi\FactionsController::byId
    methods: [GET]

factions_delete:
    path: /v1/factions/{id}
    controller: \App\Lotr\Infrastructure\Adapter\RestApi\FactionsController::remove
    methods: [DELETE]

factions_update:
    path: /v1/factions/{id}
    controller: \App\Lotr\Infrastructure\Adapter\RestApi\FactionsController::update
    methods: [PATCH]
