apiVersion: batch/v1
kind: CronJob
metadata:
    name: marketplace-events-cronjob
    namespace: marketplace
spec:
    schedule: "*/5 * * * *"
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: cronjob
                          image: docker.io/your-repo/your-php-image:latest
                          imagePullPolicy: IfNotPresent
                          envFrom:
                              -   configMapRef:
                                      name: app-config
                          command: ["console", "marketplace:events:from-provider"]
                    restartPolicy: OnFailure
