apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: my-app-ingress
    namespace: marketplace
    annotations:
        nginx.ingress.kubernetes.io/add-base-url: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, Accept"
        nginx.ingress.kubernetes.io/proxy-set-headers: "marketplace/ingress-proxy-headers"
        nginx.ingress.kubernetes.io/use-forwarded-headers: "true"

spec:
    rules:
        - host: app.example.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: nginx-service
                            port:
                                number: 80
        - host: openapi.app.example.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: swagger-service
                            port:
                                number: 8080
        - host: asyncapi.app.example.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: asyncapi-service
                            port:
                                number: 80
        - host: rabbitmq.app.example.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: rabbitmq-service
                            port:
                                number: 15672


---
apiVersion: v1
kind: ConfigMap
metadata:
    name: ingress-proxy-headers
    namespace: marketplace
data:
    Authorization: "$http_authorization"

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: allow-ingress
    namespace: marketplace
spec:
    podSelector: {}
    ingress:
        - from:
              - namespaceSelector: {}
                podSelector: {}
