apiVersion: v1
kind: Service
metadata:
    name: swagger-service
    namespace: marketplace
spec:
    selector:
        app: swagger
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
    type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: swagger-deployment
    namespace: marketplace
spec:
    replicas: 1
    selector:
        matchLabels:
            app: swagger
    template:
        metadata:
            labels:
                app: swagger
        spec:
            initContainers:
                - name: swagger-init
                  image: docker.io/your-repo/your-php-image:latest
                  imagePullPolicy: IfNotPresent
                  command: [ "sh", "-c", "cp -r docs/* /docs/" ]
                  volumeMounts:
                      - name: docs
                        mountPath: /docs
            containers:
                - name: swagger
                  image: swaggerapi/swagger-ui
                  env:
                      - name: SWAGGER_JSON
                        value: "/docs/openapi.yaml"
                  volumeMounts:
                      - name: docs
                        mountPath: /docs
            volumes:
                - name: docs
                  persistentVolumeClaim:
                      claimName: docs-pvc
