apiVersion: v1
kind: Service
metadata:
    name: swagger-service
    namespace: marketplace
spec:
    selector:
        app: swagger
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: swagger-deployment
    namespace: marketplace
spec:
    replicas: 1
    selector:
        matchLabels:
            app: swagger
    template:
        metadata:
            labels:
                app: swagger
        spec:
            containers:
                - name: swagger
                  image: swaggerapi/swagger-ui
                  env:
                      - name: SWAGGER_JSON
                        value: "/docs/openapi.yaml"
                  volumeMounts:
                      - name: docs
                        mountPath: /docs
            volumes:
                - name: docs
                  persistentVolumeClaim:
                      claimName: docs-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: docs-pvc
    namespace: marketplace
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi