openapi: 3.0.0
info:
    title: Users API
    description: API for user management in the system.
    version: 1.0.0
paths:
    /v1/users:
        post:
            summary: Create a new user
            operationId: createUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: string
                                email:
                                    type: string
                                role:
                                    type: string
                                password:
                                    type: string
                            required:
                                - id
                                - email
                                - role
                                - password
            responses:
                200:
                    description: User successfully created
                400:
                    description: Invalid request
                409:
                    description: User already exists
    /v1/users/{id}:
        get:
            summary: Get user by ID
            operationId: getUserById
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description: User found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: string
                                    email:
                                        type: string
                                    role:
                                        type: string
                404:
                    description: User not found
        delete:
            summary: Delete a user
            operationId: deleteUser
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description: User successfully deleted
                404:
                    description: User not found
        patch:
            summary: Update user information
            operationId: updateUser
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                role:
                                    type: string
                            required:
                                - email
                                - role
            responses:
                200:
                    description: User successfully updated
                400:
                    description: Invalid request
                404:
                    description: User not found
                409:
                    description: Email is already in use
    /v1/login:
        post:
            summary: User login
            operationId: loginUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                password:
                                    type: string
                            required:
                                - email
                                - password
            responses:
                200:
                    description: Login successful
                401:
                    description: Invalid credentials
components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: string
                email:
                    type: string
                role:
                    type: string
