name: Testing Workflow

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            db:
                image: postgres:15.7-alpine
                ports:
                    - 5432:5432
                env:
                    POSTGRES_USER: guest
                    POSTGRES_PASSWORD: guest
                options: >-
                    --health-cmd="pg_isready -U guest"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Build PHP Docker Image
              run: docker build -t php-app:latest --target=ci -f docker/php/Dockerfile .

            - name: Run Migrations
              run: docker run --rm php-app:latest php bin/console app:environment:init

            - name: Run Composer Validation
              run: docker run --rm php-app:latest composer validate --strict

            - name: Run Composer Audit
              run:  docker run --rm php-app:latest composer audit

            - name: Run Unit Tests
              run: docker run --rm php-app:latest phpunit --configuration phpunit.xml.dist --coverage-text --order=random

            - name: Run Acceptance Tests
              run: docker run --rm php-app:latest behat --strict --stop-on-failure --format progress

            - name: Run PHPStan
              run: docker run --rm php-app:latest phpstan analyse -l 8 src

            - name: Run PHP Code Sniffer
              run: docker run --rm php-app:latest phpcs --standard=phpcs.xml.dist
